[workspace]
resolver = "2"
members = [
    "swarm",
    "swarm_py",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
authors = ["Aleksander Lovric <alexlovric@gmail.com>"]
license = "MIT"
repository = "https://github.com/alexlovric/swarm" 
